name: Create Release

on: workflow_dispatch

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(node -p "require('./package.json').version")
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        permissions:
          contents: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
